// Generated by https://quicktype.io

import '../../../auth/domain/entities/user.dart';

class Driver {
  int idUsuario;
  Usuario usuario;

  Driver({
    required this.idUsuario,
    required this.usuario,
  });
}
