// Generated by https://quicktype.io

class User {
  int id;
  String nombre;
  String apellido;
  String correo;
  String token;
  String? foto;

  User({
    required this.id,
    required this.nombre,
    required this.apellido,
    required this.correo,
    required this.token,
    this.foto,
  });
}
